### PR TITLE
Support for german heading language and coreproperties enhancement

### PR DESCRIPTION
**Pull request by rskis**
The coreproperties enhancement turns default category and description values to parameters keeping the original signature.

### CODE REVIEW

**Comment by scanny** [comment]
Hi rskis, we're working on a new, object-oriented release of python-docx so we're not merging any new pull requests into the old version. I'll keep this enhancement on file though and make sure the new version supports these requirements as soon as possible.

**Comment by rskis** [comment]
Hi scanny,

ok, thanks for the feedback.
Do you have any estimate on when you will release you're OO version?

Regards,

Ralf

Am 09.07.2013 02:34, schrieb scanny:

**Comment by scanny** [comment]
I just completed it as far as round-tripping a document without making any changes to it this weekend.

I know that doesn't sound like much from a feature standpoint, but it gives the foundation upon which we can incrementally build individual features, all without losing existing elements from the document (like headers, for example).

So I'd say a first release should come out within about 45 days, although it's probably closer to 90 days before it's got feature parity with the current version.

I'm not sure about that though, I'm hopeful we can move more quickly since it's reimplementation of existing functionality, but my experience is telling me there are unseen challenges between here and there and that the 90 day estimate is probably the most likely :)

What's the use case you're pursuing?

--Steve

**Comment by rskis** [comment]
Hi Steve,

ok, thanks for the timeline.

For now we will go with the personal docx version I've created.
After your realse of the new docx version I guess we will simply switch over.
This should hopefully be not too difficult... ;-)

regards,

Ralf

**Pull request closed without merging**
