### PR TITLE
Switch setup.py to setuptools for better dependency installation

### PR DESCRIPTION
**Pull request by bjlange**
Current setup.py file doesn't install dependencies correctly when using 'pip install docx'. This should fix that.

### CODE REVIEW

**Comment by scanny** [comment]
Hi Brian, thanks for this :)

Couple things:
- does this work with `distutils`? Have you tested it? The setup.py for python-docx imports setup from `distutils` and last time I checked `install_requires` only works with `setuptools`.
- assuming you get that sorted, could you combine these three changes in a single commit? That will keep it clear they're all part of a single update intent.

**Comment by bjlange** [comment]
I've only tested with my local copy of pip, which I believe uses setuptools by default, but I'm not sure. I'll look into it now and let you know what I find.

**Comment by bjlange** [comment]
OK, when just running `setup.py install` locally (with the latest version of distutils, 2.7.5), it throws a warning: `UserWarning: Unknown distribution option: 'install_requires'`, but it still installs, just sans dependencies. So no, it doesn't strictly work with distutils, but functionally it does the same thing as before. Pip somehow figures things out and uses setuptools (or distribute) to install the dependencies. I added another note to the README mentioning that setuptools and pip are required to do it this way. 

It's up to you as to whether you want to merge this change in or not- if you want to keep it pure distutils and warning-free without any automated dependency installation, that's your call. I can use my own fork for pip/setuptools-dependent stuff.

**Comment by scanny** [comment]
I was thinking more along the lines of switching over to setuptools altogether so dependencies could be supported.

But after doing a quick search on that question I came across this [try/catch method](https://github.com/dcramer/pyflakes/blob/3f7aa2a9267fbb8ec814ccbaf985e7bc1293ce48/setup.py) where you can use setuptools if it's installed and fall back to distutils if setuptools (or distribute) is not installed.

What do you think about that approach? I think adding dependency installation would be a nice enhancement and I'm thinking this would make the best of whatever the installer's environment allowed.

**Comment by bjlange** [comment]
That seems to be a common pattern in some other packages, looks good to me. Do you want me to include that in this pull request or are you going to do that separately?

**Comment by scanny** [comment]
Might as well put it all together, that would be great if you could include it :)

**Comment by bjlange** [comment]
Alright, it's in there. I didn't mess around with any additional setuptools features, but I did test what's there both with pip and by running `setup.py install`\- it works both ways.

**Comment by scanny** [comment]
Thanks Brian :)

**Pull request merged**
