### PR TITLE
docx.py -> opendocx

### PR DESCRIPTION
**Pull request by iyad-obeid**
I modified the opendocx function in docx.py to allow it to open other xml files than just document.xml. Its now capable of opening all three header and footer xml files as well. I used this functionality to create a script that would extract text from a full document (header, body, footer) not just the body (as the example code does). I thought it was useful and I thought others might like it too. The code is backwards compatible, so if you don't specify fileType, it should work just fine.

### CODE REVIEW

**Comment by scanny** [comment]
Hi @vectortronic, unfortunately the legacy versions (v0.2.x) of python-docx in this repository are maintained on a strictly bugfix-only basis, to ensure stability for projects that use it.

There is an active "new" version (currently at v0.7.4) which is a ground-up rewrite here: https://github.com/python-openxml/python-docx, with documentation here: http://python-docx.readthedocs.org/en/latest/ that you might want to check out for future projects.

We're always happy for contributions there, although it's always a good idea to reach out ahead of time to make sure your contribution will be commitable. We accept all contributions, but can only commit those that meet the guidelines :)

**Comment by scanny** [comment]
Btw @vectortronic, you somehow ended up deleting most of the project's files in your commits, which of course would definitely _not_ be committable in any case. You might want to check your Git technique there :)

**Comment by iyad-obeid** [comment]
Hey, thanks for the note. Your code really saved me a lot of trouble - I
have a great script now that can extract everything from a word docx
(including headers and footers) and formats it pretty decently.

Sorry about the github technique - although I've coded plenty and used
other version control systems before, I'm very new to Github and still
learning the ropes. Thanks for alerting me!

Best,

--Iyad

## 

Iyad Obeid, PhD
215-204-9033 / iobeid@temple.edu / www.obeidlab.com

**Comment by scanny** [comment]
No worries Iyad, glad it worked out for you :)

**Pull request closed without merging**
