### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by gtozzi**
Hi!

I've made a bug fix in AdvReplace (see commit comments for details).

Have a nice christmas time! :)

### CODE REVIEW

**Comment by mikemaccana** [comment]
Thanks! You too!

**Comment by mikemaccana** [comment]
Sorry, forgot to add this! Done. Do you want me to add you as a maintainer of the project? I;m not doing a lot with Word right now.

**Comment by gtozzi** [comment]
Hi!

Actually, I don't have enough time too to become a maintainer. I'll keep contributing my code as an external contributor.
I'm also planning to write some documentation and usage examples on the template system I wrote asap.

Thank you for your offer, but I have to refuse.

**Comment by mikemaccana** [comment]
No probs, thanks for your contributions!

**Pull request merged**
